# Generated by Django 3.0.8 on 2020-07-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('mod_date', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('pdf', models.FileField(upload_to='Docs/')),
            ],
        ),
        migrations.CreateModel(
            name='Viewers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='')),
                ('last_visit', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence_service.Doc')),
            ],
        ),
    ]
